### ISSUE TITLE
执行init_db.sh失败

### ISSUE THREAD

**Issue by yuyc** [TencentBlueKing/bk-cmdb#7235]
问题描述
===========
采用的代码是最新的版本[release-v3.10.29](https://github.com/TencentBlueKing/bk-cmdb/releases/tag/release-v3.10.29)

我的数据库相关版本,数据库使用docker compose

```
version: '3.8'

services:
  zookeeper:
    container_name: zk
    image: zookeeper:3.6.0
    ports:
      - 2181:2181

  redis:
    container_name: redis
    image: redis:3.2.11
    command: redis-server --requirepass bk-cmdb
    ports:
      - 6379:6379

  mongo:
    container_name: mongo
    image: mongo:4.4.0
    command: mongod --replSet rs0 --bind_ip_all
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: bk-cmdb
      MONGO_INITDB_DATABASE: cmdb
    ports:
      - 27017:27017
```
我创建的rs如下：
```
rs.initiate({ _id : "rs0",members: [{ _id: 0, host: "127.0.0.1:27017" }]})
```
我创建的mongo用户如下：
创建一个自定义角色用来watch
```
use admin
db.createRole({
   role: "watchRole",
   privileges: [
      { resource: { db: "", collection: "" }, actions: [ "changeStream", "find" ] }
   ],
   roles: []
})

```

```
db.updateUser({user: "cc",pwd: "bk-cmdb",roles: [ { role: "dbAdmin", db: "cmdb" }, {role: "watchRole", db: "admin"} ]})
```
我执行初始化的命令如下：
```
python init.py    --discovery          127.0.0.1:2181   --database           cmdb   --redis_ip           127.0.0.1   --redis_pass         bk_cmdb   --mongo_ip           127.0.0.1   --mongo_user cc   --mongo_pass         bk-cmdb   --blueking_cmdb_url  http://10.241.8.7:80  --listen_port        80   --auth_scheme        internal    --log_level          3   --register_ip   10.241.8.7 --user_info          admin:admin
```
================
起服务都正常，但是执行./init_db.sh时候，cmdb_adminserver报如下错误：
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0719 16:42:19.433500 3046498 configcenter/viper.go:397] config watch.maxIdleConns less than minimum value, use minimum value 50
E0719 16:42:19.449287 3046498 backbone/notice.go:57] log watch failed, will watch after 10s, path: /cc/services/notice/log/10.241.8.7:60004/v, err: zk: node does not exist
E0719 16:42:19.491967 3046498 logics/index.go:91] db not initialization is complete, rid: cc0000cirq3qs92kh70hiutlog
E0719 16:42:39.494172 3046498 logics/index.go:91] db not initialization is complete, rid: cc0000cirq3qs92kh70hiutlog
E0719 16:42:59.496432 3046498 logics/index.go:91] db not initialization is complete, rid: cc0000cirq3qs92kh70hiutlog
E0719 16:43:08.097727 3046498 x19.09.03.05/create_object_id_index.go:40] CreateObjectIDIndex failed, err: connection(127.0.0.1:27017[-94]) incomplete read of message header: read tcp 127.0.0.1:36974->127.0.0.1:27017: i/o timeout
E0719 16:43:08.097758 3046498 x19.09.03.05/pkg.go:34] CreateObjectIDIndex failed, err: CreateObjectIDIndex failed, err: connection(127.0.0.1:27017[-94]) incomplete read of message header: read tcp 127.0.0.1:36974->127.0.0.1:27017: i/o timeout
E0719 16:43:08.097765 3046498 upgrader/register.go:249] upgrade version x19_09_03_05 error: CreateObjectIDIndex failed, err: connection(127.0.0.1:27017[-94]) incomplete read of message header: read tcp 127.0.0.1:36974->127.0.0.1:27017: i/o timeout
E0719 16:43:08.097772 3046498 service/migrate.go:60] db upgrade failed, err: run migration x19_09_03_05 failed, err: CreateObjectIDIndex failed, err: connection(127.0.0.1:27017[-94]) incomplete read of message header: read tcp 127.0.0.1:36974->127.0.0.1:27017: i/o timeout, rid: cc0000cirq44k92kh70hiutlp0

请问这是什么原因呢
