### ISSUE TITLE
【CMDB+v3.12.2】全文检索提示“查询检索内容不存在”

### ISSUE THREAD

**Issue by fadding** [TencentBlueKing/bk-cmdb#7596]
**全文检索开启后，提示检索内容不存在**

开启全文检索后，monstache 也配置正常，启动后，前端搜索，报错，查看服务端topo server模块日志，得到错误 
```txt
err: elastic: Error 404 (Not Found):
no such index [bk_cmdb.bk_biz_set_obj] [type=index_not_found_exception], rid: cc0000cndfrnjesz1g0002s4b0
E1120 14:27:34.374548
3251 service/fulltextsearch.go:7571 rid: cc0000cndfrnjesz1g0002s4b0,
err:
```

**预期行为**

能正常查询到创建的资源模型的实例化数据

**版本**
- v3.12.2

**如果是页面问题，请提供使用的操作系统和浏览器信息**
 - OS: macos
 - Browser chrome
 - Version 版本 119.0.6045.159（正式版本） (arm64)

**额外信息**

1. 查看mongo对应的db库，已经存在了很多cc_ObjectBase_0_pub_xxx 表
2. 编译出来的monstache对应的两项同步的配置如下
```toml
# metadata collections.
change-stream-namespaces = [""]
direct-read-namespaces = [""]
direct-read-dynamic-include-regex = "cmdb.cc_ApplicationBase$|cc_SetBase$|cc_ModuleBase$|cmdb.cc_HostBase$|cmdb.cc_ObjDes$|cc_ObjAttDes$|cmdb.cc_ObjectBase_(.*)_pub_"
namespace-regex = "cmdb.cc_ApplicationBase$|cc_SetBase$|cc_ModuleBase$|cmdb.cc_HostBase$|cmdb.cc_ObjDes$|cc_ObjAttDes$|cmdb.cc_ObjectBase_(.*)_pub_"

```
