### ISSUE TITLE
cmdb_adminserver启动报错：连接不上mongodb

### ISSUE THREAD

**Issue by yulichun** [TencentBlueKing/bk-cmdb#8292]
**用文字描述你遇到的问题**

cmdb_adminserver启动报错：
E1204 09:19:49.814961    9261 mongodb/monogdb.go:94] failed to connect the mongo server, error info is init id generator but get config admin failed, err: server selection error: server selection timeout, current topology: { Type: ReplicaSetNoPrimary, Servers: [] }
E1204 09:19:49.815175    9261 admin_server/migrate.go:52] process stopped by connect mongo server failed '.mongodb' initialization failed

**重现方法**

部署的单机mongodb，mongodb与cmdb部署在一个机器。

mongodb为单机模式，连接情况正常：
```
root@localhost:/opt/cmdb/cmdb_adminserver/logs# /opt/mongodb/bin/mongo --host 127.0.0.1 --port 27017 -u cc -p cc --authenticationDatabase cmdb
MongoDB shell version v4.2.8
connecting to: mongodb://127.0.0.1:27017/?authSource=cmdb&compressors=disabled&gssapiServiceName=mongodb
Implicit session: session { "id" : UUID("2ef6ccbc-ca0b-4b7c-8517-a90e860d4e31") }
MongoDB server version: 4.2.8
> use cmdb
switched to db cmdb
> exit
bye
```

/opt/cmdb/cmdb_adminserver/configures/mongodb.yaml:
```
root@localhost:/opt/cmdb/cmdb_adminserver/configures# cat mongodb.yaml 

#mongodb:
#  host: 127.0.0.1
#  port: 27017
#  usr: cc
#  pwd: cc
#  database: cmdb
#  maxOpenConns: 3000
#  maxIdleConns: 100
#  mechanism: SCRAM-SHA-1
#  rsName: rs0

# mongodb配置
mongodb:
  host: 127.0.0.1
  port: 27017
  usr: cc
  pwd: "cc"
  database: cmdb
  maxOpenConns: 3000
  maxIdleConns: 100
  mechanism: SCRAM-SHA-1
  rsName: rs0
  #mongo的socket连接的超时时间，以秒为单位，默认10s，最小5s，最大30s。
  socketTimeoutSeconds: 10
  # mongodb事件监听存储事件链的mongodb配置
watch:
  host: 127.0.0.1
  port: 27017
  usr: cc
  pwd: "cc"
  database: cmdb
  maxOpenConns: 10
  maxIdleConns: 5
  mechanism: SCRAM-SHA-1
  rsName: rs0
  socketTimeoutSeconds: 10
```

**预期行为**

预期cmdb_adminserver能正常启动

**版本**
- 3.13.12
